from torch.cuda import is_available

SOS_TOKEN = 0
EOS_TOKEN = 1
PAD_TOKEN = 2
UNK_TOKEN = 3
MAX_LENGTH = 10
BATCH_SIZE = 32
USE_CUDA = is_available()
STORE_DATA_ON_GPU_IF_AVAILABLE = False
TRAIN_TEST_SPLIT = 0.1
TRAIN_VALID_SPLIT = 0.1
HIDDEN_SIZE = 64
EMBEDDING_DROPOUT = 0.2
INTER_RECURRENT_LAYER_DROPOUT = 0.2
INTRA_RECURRENT_LAYER_DROPOUT = 0.2
STATISTICS_FILE = 'statistics.csv'
EPOCHS = 10
PATIENCE = 5
BEAM_WIDTH = 3
TEACHER_FORCING_PROPORTION_START = 1.
EMBEDDING_DIMENSION = 64
ATTENTION_HEADS = 4
FEEDFORWARD_DIMENSION = 512
POSITIONAL_ENCODER_DROPOUT = 0.2
MIN_OCCURENCES = 2
TEACHER_FORCING_SCALE_FACTOR = 0.95
